[package]
name = "brain_rust"
version = "0.1.1"
edition = "2018"

authors = ["kennet <kennetam02@gmail.com>"] 

[[bin]]
name = "brain_rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
read_input = "0.8.6"